### ISSUE TITLE
Crash on peripheral block break

### ISSUE THREAD

**Issue by mj-sakellaropoulos** [uecasm/rs4cc#5]
Client or server will crash if the Refined Storage peripheral is broken while connected to a Refined Storage network and computer

Mod versions: 
- forge : 35.1.13
- rs4cc : Storage4ComputerCraft-1.16.4-1.2.0.jar
- refined : refinedstorage-1.9.11.jar
- applied : appliedenergistics2-8.2.0-beta.2.jar

```
[20:25:30] [Server thread/WARN] [computercraft/]: Lua Method nz.co.mirality.storage4computercraft.integration.refinedstorage.RSPeripheral.getItem should be final.
[20:25:30] [Server thread/WARN] [computercraft/]: Lua Method nz.co.mirality.storage4computercraft.integration.refinedstorage.RSPeripheral.getFluid should be final.
[20:25:38] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: No network node present at BlockPos{x=167, y=67, z=-67}, consider removing the block at this position
	Index: 13
	Listeners:
		0: NORMAL
		1: ASM: class com.feed_the_beast.mods.ftbessentials.FTBEEventHandler serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		2: ASM: com.github.alexthe666.citadel.server.CitadelEvents@144549e1 onServerTickEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		3: ASM: class net.xalcon.torchmaster.common.logic.entityblocking.EntityBlockingEventHandler onGlobalTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		4: ASM: class owmii.lib.util.Server tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		5: ASM: class se.mickelus.tetra.ServerScheduler onPlayerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		6: net.minecraftforge.eventbus.EventBus$$Lambda$2437/820982507@520e2761
		7: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		8: net.minecraftforge.eventbus.EventBus$$Lambda$2437/820982507@58801912
		9: ASM: class dan200.computercraft.shared.peripheral.monitor.MonitorWatcher onTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		10: ASM: class dan200.computercraft.shared.proxy.ComputerCraftProxyCommon$ForgeHandlers onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		11: ASM: class dan200.computercraft.shared.util.TickScheduler tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda$2437/820982507@6ddb995e
		13: ASM: class nz.co.mirality.storage4computercraft.util.ServerWorker serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		14: net.minecraftforge.eventbus.EventBus$$Lambda$2437/820982507@5e109629
		15: ASM: net.minecraftforge.common.ForgeInternalHandler@cadbadb onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		16: ASM: me.desht.pneumaticcraft.common.event.TickHandlerPneumaticCraft@514ac6ed onServerTickEnd(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		17: ASM: class cofh.ensorcellation.event.CommonEvents handleTickEndEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		18: ASM: class com.simibubi.create.events.CommonEvents onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		19: ASM: class vazkii.psi.common.core.handler.PlayerDataHandler$EventHandler onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		20: net.minecraftforge.eventbus.EventBus$$Lambda$2437/820982507@7d0687a5
		21: ASM: class com.feed_the_beast.mods.ftbbackups.FTBBackups serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		22: ASM: class sonar.fluxnetworks.register.CommonEventHandler onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		23: ASM: class com.minecolonies.coremod.event.FMLEventHandler onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		24: net.minecraftforge.eventbus.EventBus$$Lambda$2437/820982507@2516499e
		25: ASM: mekanism.common.CommonWorldTickHandler@5e05480d onTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		26: ASM: Network Registry:
{} onTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		27: ASM: codechicken.enderstorage.network.TankSynchroniser@42ea70b7 tickEnd(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		28: ASM: class com.direwolf20.mininggadgets.common.events.ServerTickHandler handleTickEndEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		29: LOWEST
		30: ASM: class cofh.core.event.AreaEffectEvents handleTickEndEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
java.lang.IllegalStateException: No network node present at BlockPos{x=167, y=67, z=-67}, consider removing the block at this position
	at com.refinedmods.refinedstorage.tile.NetworkNodeTile.getNode(NetworkNodeTile.java:65)
	at nz.co.mirality.storage4computercraft.integration.refinedstorage.RSPeripheral.getNode(RSPeripheral.java:46)
	at nz.co.mirality.storage4computercraft.integration.refinedstorage.RSPeripheral.lambda$detach$1(RSPeripheral.java:66)
	at nz.co.mirality.storage4computercraft.util.ServerWorker.serverTick(ServerWorker.java:24)
	at net.minecraftforge.eventbus.ASMEventHandler_501_ServerWorker_serverTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:120)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:827)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
	at java.lang.Thread.run(Thread.java:748)

[20:25:38] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.IllegalStateException: No network node present at BlockPos{x=167, y=67, z=-67}, consider removing the block at this position
	at com.refinedmods.refinedstorage.tile.NetworkNodeTile.getNode(NetworkNodeTile.java:65) ~[refinedstorage:1.9.11] {re:classloading}
	at nz.co.mirality.storage4computercraft.integration.refinedstorage.RSPeripheral.getNode(RSPeripheral.java:46) ~[storage4computercraft:1.2.0] {re:classloading}
	at nz.co.mirality.storage4computercraft.integration.refinedstorage.RSPeripheral.lambda$detach$1(RSPeripheral.java:66) ~[storage4computercraft:1.2.0] {re:classloading}
	at nz.co.mirality.storage4computercraft.util.ServerWorker.serverTick(ServerWorker.java:24) ~[storage4computercraft:1.2.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_501_ServerWorker_serverTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:120) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:827) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] {}
[20:25:38] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 2d744426-cf14-4fc7-afbe-f5c8667ed4f5
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
Clipboard copy at: 10 Jan 2021 20:26:39 -0500
```

**Comment by uecasm** [comment]
Thanks for the report.  This should now be fixed in 1.2.1, which will be on CurseForge momentarily.
