### ISSUE TITLE
peripheral block stopped working

### ISSUE THREAD

**Issue by kmchenHH** [uecasm/rs4cc#9]
![Screenshot_1](https://user-images.githubusercontent.com/45352326/134228391-ac1ab17c-3693-4f9c-97ee-1373e9080ceb.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/45352326/134228395-5fb42d19-5f27-448a-b000-3d2373c622f1.jpg)
Without warning and without any other problems any attempt using the rs.getItems()-Method on any cc-Advanced Computer connected to a rs-peripheral-block of our main storage rs-system failed and each attempt throws an error (list below). All other peripheral-blocks on our other rs- and me-systems are working just fine.

Env: 
ATM 6 1.6.5
MC  1.16.5
Forge 36.1.24
added Mods:
morered_computercraft_integration-1.16.5-1.0.0.0
Storage4ComputerCraft-1.16.5-1.3.1
cc-tweaked-1.16.5-1.98.2

Server-Log :
[21Sep2021 19:48:51.743] [Server thread/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
[21Sep2021 19:48:51.743] [Server thread/ERROR] [computercraft/]: Error running task
java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.1.24.jar:36.1]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
	at com.buuz135.industrial.item.infinity.ItemInfinity.getDurabilityForDisplay(ItemInfinity.java:198) ~[industrialforegoing:3.2.11]
	at dan200.computercraft.shared.peripheral.generic.data.ItemData.fill(ItemData.java:66) ~[computercraft:1.98.2]
	at nz.co.mirality.storage4computercraft.util.StackConverter.convertStack(StackConverter.java:36) ~[storage4computercraft:1.3.1]
	at nz.co.mirality.storage4computercraft.util.StackConverter.convert(StackConverter.java:18) ~[storage4computercraft:1.3.1]
	at nz.co.mirality.storage4computercraft.util.LuaConversion.convert(LuaConversion.java:51) ~[storage4computercraft:1.3.1]
	at nz.co.mirality.storage4computercraft.util.LuaConversion$CollectionConverter.convert(LuaConversion.java:72) ~[storage4computercraft:1.3.1]
	at nz.co.mirality.storage4computercraft.util.LuaConversion.convert(LuaConversion.java:51) ~[storage4computercraft:1.3.1]
	at nz.co.mirality.storage4computercraft.integration.refinedstorage.RSPeripheral.getItems(RSPeripheral.java:641) ~[storage4computercraft:1.3.1]
	at nz.co.mirality.storage4computercraft.integration.refinedstorage.RSPeripheral$cc$getItems166.apply(CC generated method) ~[?:?]
	at dan200.computercraft.core.asm.PeripheralMethod.lambda$null$0(PeripheralMethod.java:21) ~[computercraft:1.98.2]
	at dan200.computercraft.core.lua.LuaContext.lambda$issueMainThreadTask$0(LuaContext.java:36) ~[computercraft:1.98.2]
	at dan200.computercraft.core.computer.MainThreadExecutor.execute(MainThreadExecutor.java:143) ~[computercraft:1.98.2]
	at dan200.computercraft.core.computer.MainThread.executePendingTasks(MainThread.java:157) ~[computercraft:1.98.2]
	at dan200.computercraft.shared.CommonHooks.onServerTick(CommonHooks.java:59) ~[computercraft:1.98.2]
	at net.minecraftforge.eventbus.ASMEventHandler_1079_CommonHooks_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreServerTick(BasicEventHooks.java:115) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:785) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by uecasm** [comment]
This is a bug in Industrial Foregoing; they're doing something client-only on the server side during an interaction with CC:Tweaked.  Report it to them.

In the meantime, you can work around this by removing all "Infinity" tools from the RS system.

**Comment by kmchenHH** [comment]
Thank you for this information - found one Infinity-Hammer and now our System is working fine again. Thank you very much.
